# Generated by Django 5.2.1 on 2025-05-25 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cedula', models.CharField(default='0000', max_length=20, unique=True)),
                ('nro_matricula', models.CharField(default=0)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('CI', models.CharField(max_length=30)),
                ('fechaNacimieto', models.DateField()),
                ('sexo', models.BooleanField(default=False)),
                ('fechaIngreso', models.DateField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(max_length=30)),
                ('observaciones', models.TextField(max_length=200)),
                ('transfucion', models.BooleanField(default=False)),
                ('transfucionMotivo', models.CharField(max_length=100)),
                ('cirugia', models.BooleanField(default=False)),
                ('cirugiaMotivo', models.CharField(max_length=100)),
                ('sangra', models.BooleanField(default=False)),
                ('fuma', models.BooleanField(default=False)),
                ('haceCuantoFuma', models.CharField(max_length=100)),
                ('cuantoFuma', models.CharField(max_length=100)),
                ('toma', models.BooleanField(default=False)),
                ('haceCuantoToma', models.CharField(max_length=100)),
                ('cuantoToma', models.CharField(max_length=100)),
                ('embarazo', models.IntegerField(default=0)),
                ('semanasEmbarazo', models.IntegerField(default=0)),
                ('anestesia', models.IntegerField(default=0)),
                ('testElisa', models.BooleanField(default=False)),
                ('haceCuantoTestElisa', models.CharField(max_length=100)),
                ('antecedentesFamiliares', models.ManyToManyField(to='CGOdonto.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('odotologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGOdonto.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGOdonto.paciente')),
                ('tratamiento', models.ManyToManyField(to='CGOdonto.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='planTratamientoEntregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('planTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGOdonto.plantratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGOdonto.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGOdonto.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGOdonto.tratamiento')),
            ],
        ),
    ]
